apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-bitkmbxa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/sjmrhtap/nodejs-bitkmbxa:aa7149be0f28d407c94115b3cbc6ed7dd0194ce4
          name: container-image
